### Crear cuenta de cliente en DB.
POST http://localhost:3000/auth/local/register
Content-Type: application/json

{
    "fullname": "Josedeodot",
    "mail": "josedeodods22@gmail.com",
    "password": "Makakzak21|A"
} 

### Login de cliente en DB.
POST http://localhost:3000/auth/jwt/login
Content-Type: application/json

{
    "mail": "cristianalonso@gmail.com",
    "password": "123456Ca"
}

### Crear un trabajador en DB.
POST http://localhost:3000/auth/local/register/worker
Content-Type: application/json

{
    "fullname": "Francisco Perez",
    "mail": "franutnf23@gmail.com",
    "password": "Makaak2S!Ado",
    "phone": "3815412480",
    "address": "Calle falsa 123"
} 

### Login de trabajador en DB.
POST http://localhost:3000/auth/local/login
Content-Type: application/json

{
    "mail": "franutnf23@gmail.com",
    "password": "Makaak2S!Ado"
}



### Logout de cliente en DB.
GET http://localhost:3000/auth/logout


### Logueo d en DB.
POST http://localhost:3000/auth/jwt/login
Content-Type: application/json
{
    "mail": "franutnf23@gmail.com",
    "password": "Makaak2S!Ado"
}