### Create Worker
POST /worker/create HTTP/1.1
Content-Type: application/json

{
    "fullname": "John Doe",
    "dni": "12345678",
    "email": "johndoe@example.com",
    "phone": "1234567890",
    "address": "123 Main St",
    "birthdate": "1990-01-01"
}

### Get All Workers
GET localhost:3000/users/find-all HTTP/1.1

### Get Worker By ID
GET /worker/find-by-id/{workerId} HTTP/1.1

### Get Worker By Fullname
GET /worker/find-by-fullname/{fullname} HTTP/1.1

### Update Worker
PUT /worker/update/{workerId} HTTP/1.1
Content-Type: application/json

{
    "email": "newemail@example.com",
    "phone": "9876543210",
    "address": "456 Elm St",
    "birthdate": "1990-02-02",
    "img": "https://example.com/profile.jpg"
}

### Delete Worker
DELETE /worker/delete/{workerId} HTTP/1.1