### Obtener todos los usuaios
GET http://localhost:3000/user/

### Actualizar la imagen de un usuario
PATCH http://localhost:3000/user/updateImg/66b4634a6d5714558d757945
Content-Type: application/json

{
    "img": "hola2"
}

### Actualizar contraseña de un usuario.
PATCH http://localhost:3000/user/updatePassword/66b4634a6d5714558d75793c
Content-Type: application/json

{
    "password": "Makak2S!Ado21"
}
