### Obtener todos los trabajadores
GET http://localhost:3000/worker/

### Obtener un trabajador por ID.
GET http://localhost:3000/worker/66b433ad023c76f14a17be03

### Obtener un trabajador por nombre
GET http://localhost:3000/worker/l